# Read the documentation: https://github.com/hautelook/AliceBundle/blob/v1.4.1/README.md
hautelook_alice:
    fixtures_path: 'src/Resources/Fixtures/ORM' # Path to which to look for fixtures relative to the bundle path.
#    db_drivers:
#        orm: ~
#    locale: en_US
#    seed: 1
#    persist_once: false
#    loading_limit: 5
